baseURL = 'https://alstan.art/'
title = 'Alstan'
theme = 'lightbi-hugo'

defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true
[languages]
  [languages.fr]
    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr_FR'
    languageDirection = 'ltr'
    languageName = 'French'

